param(
    [string]$CandidateId,
    [string]$InstanceId,
    [int]$Seed,
    [string]$Instance,
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$ParameterArgs
)

$ErrorActionPreference = "Stop"

function Resolve-RunnerPath {
    param([string]$Path)

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return (Resolve-Path -LiteralPath $Path).Path
    }

    return (Resolve-Path -LiteralPath (Join-Path $script:ScriptDir $Path)).Path
}

function Get-JuliaExe {
    $juliaCmd = Get-Command julia -ErrorAction SilentlyContinue
    if ($juliaCmd -and ($juliaCmd.Source -notlike "*\Microsoft\WindowsApps\*")) {
        return $juliaCmd.Source
    }

    $candidate = Get-ChildItem -Path "$HOME\.julia\juliaup" -Recurse -Filter "julia.exe" -ErrorAction SilentlyContinue |
        Sort-Object FullName -Descending |
        Select-Object -First 1

    if ($candidate) {
        return $candidate.FullName
    }

    throw "Julia not found."
}

function ConvertTo-ParameterMap {
    param([string[]]$Args)

    $map = @{
        population_size = "2000"
        elite_percentage = "0.30"
        mutants_percentage = "0.15"
        reset_interval = "0"
    }

    for ($i = 0; $i -lt $Args.Count; $i += 2) {
        $name = $Args[$i].TrimStart("-")
        $value = $Args[$i + 1]
        $map[$name] = $value
    }

    return $map
}

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = (Resolve-Path -LiteralPath (Join-Path $ScriptDir "..\..")).Path
$InstancePath = Resolve-RunnerPath $Instance
$JuliaExe = Get-JuliaExe
$Params = ConvertTo-ParameterMap $ParameterArgs

$RunDir = Join-Path $ScriptDir "runs"
New-Item -ItemType Directory -Path $RunDir -Force | Out-Null

$safeId = "$CandidateId-$InstanceId-$Seed" -replace "[^A-Za-z0-9_.-]", "_"
$ConfigFile = Join-Path $RunDir "$safeId.conf"
$OutputCsv = Join-Path $RunDir "$safeId.csv"
$LogFile = Join-Path $RunDir "$safeId.log"

Remove-Item -LiteralPath $ConfigFile, $OutputCsv, $LogFile -ErrorAction SilentlyContinue

$configText = @"
# Generated by IRACE/BRKGA/target-runner.ps1
population_size $($Params.population_size)
elite_percentage $($Params.elite_percentage)
mutants_percentage $($Params.mutants_percentage)
num_elite_parents 1
total_parents 2
bias_type LOGINVERSE
num_independent_populations 1
pr_number_pairs 0
pr_minimum_distance 0.15
pr_type PERMUTATION
pr_selection BESTSOLUTION
alpha_block_size 1.0
pr_percentage 1.0
exchange_interval 0
num_exchange_indivuduals 0
reset_interval $($Params.reset_interval)
"@

Set-Content -LiteralPath $ConfigFile -Value $configText -Encoding ASCII

$juliaArgs = @(
    "--project=BRKGA",
    "BRKGA/main.jl",
    $ConfigFile,
    $InstancePath,
    $Seed,
    "200",
    $OutputCsv
)

Push-Location $ProjectRoot
try {
    & $JuliaExe @juliaArgs *> $LogFile
    if ($LASTEXITCODE -ne 0) {
        throw "Julia returned exit code $LASTEXITCODE. See $LogFile"
    }
} finally {
    Pop-Location
}

$result = Import-Csv -LiteralPath $OutputCsv | Select-Object -First 1
[Console]::Out.WriteLine($result.bestSpan)
